import type {
  User,
  DroppingArea,
  SellerProfile,
  Partnership,
  Item,
  Transaction,
  AppNotification,
} from './types';

const now = new Date();
const d = (offsetDays: number) => new Date(now.getTime() + offsetDays * 86400000).toISOString();

// ─── Mock Users ───────────────────────────────────────────────────────────────
export const MOCK_USERS: User[] = [
  {
    id: 'user-buyer-1',
    full_name: 'Maria Santos',
    email: 'buyer@demo.com',
    phone: '+63 912 345 6789',
    is_seller: false,
    role: 'buyer',
    created_at: d(-30),
  },
  {
    id: 'user-seller-1',
    full_name: 'Juan dela Cruz',
    email: 'seller@demo.com',
    phone: '+63 917 654 3210',
    is_seller: true,
    role: 'seller',
    created_at: d(-60),
  },
  {
    id: 'user-seller-2',
    full_name: 'Ana Reyes',
    email: 'seller2@demo.com',
    phone: '+63 918 111 2222',
    is_seller: true,
    role: 'seller',
    created_at: d(-45),
  },
  {
    id: 'user-seller-3',
    full_name: 'Pedro Villanueva',
    email: 'seller3@demo.com',
    phone: '+63 919 333 4444',
    is_seller: true,
    role: 'seller',
    created_at: d(-50),
  },
  {
    id: 'user-hubadmin-1',
    full_name: 'Rose Baguio',
    email: 'hubadmin@demo.com',
    phone: '+63 920 555 6666',
    is_seller: false,
    role: 'hub_admin',
    created_at: d(-90),
  },
  {
    id: 'user-admin-1',
    full_name: 'Super Admin',
    email: 'admin@demo.com',
    phone: '+63 921 777 8888',
    is_seller: false,
    role: 'super_admin',
    created_at: d(-120),
  },
];

// ─── Demo Credentials ─────────────────────────────────────────────────────────
// buyer@demo.com / password
// seller@demo.com / password
// hubadmin@demo.com / password
// admin@demo.com / password
export const DEMO_PASSWORDS: Record<string, string> = {
  'buyer@demo.com': 'password',
  'seller@demo.com': 'password',
  'seller2@demo.com': 'password',
  'seller3@demo.com': 'password',
  'hubadmin@demo.com': 'password',
  'admin@demo.com': 'password',
};

// ─── Dropping Areas ───────────────────────────────────────────────────────────
export const MOCK_DROPPING_AREAS: DroppingArea[] = [
  {
    id: 'area-1',
    name: 'Session Road Hub',
    address: '22 Session Road, Baguio City',
    latitude: 16.4118,
    longitude: 120.5956,
    contact_info: '+63 74 442 1100',
    admin_user_id: 'user-hubadmin-1',
    status: 'active',
    created_at: d(-90),
  },
  {
    id: 'area-2',
    name: 'Burnham Park Hub',
    address: 'Burnham Park Perimeter Road, Baguio City',
    latitude: 16.4120,
    longitude: 120.5961,
    contact_info: '+63 74 442 2200',
    admin_user_id: 'user-hubadmin-1',
    status: 'active',
    created_at: d(-60),
  },
  {
    id: 'area-3',
    name: 'Mines View Hub',
    address: 'Mines View Road, Baguio City',
    latitude: 16.4341,
    longitude: 120.6261,
    contact_info: '+63 74 442 3300',
    admin_user_id: 'user-hubadmin-1',
    status: 'active',
    created_at: d(-45),
  },
];

// ─── Seller Profiles ──────────────────────────────────────────────────────────
export const MOCK_SELLER_PROFILES: SellerProfile[] = [
  {
    id: 'seller-1',
    user_id: 'user-seller-1',
    business_name: 'Baguio Finds',
    bio: 'Curated thrift and pre-loved items from the City of Pines. Quality pieces at great prices.',
    verified: true,
    created_at: d(-55),
  },
  {
    id: 'seller-2',
    user_id: 'user-seller-2',
    business_name: 'Pine City Goods',
    bio: 'Authentic Baguio local products — strawberry preserves, ukay-ukay finds, and more.',
    verified: true,
    created_at: d(-40),
  },
  {
    id: 'seller-3',
    user_id: 'user-seller-3',
    business_name: 'Session Style Co.',
    bio: 'Trendy fashion finds at Session Road prices. New arrivals every week.',
    verified: false,
    created_at: d(-42),
  },
];

// ─── Partnerships ─────────────────────────────────────────────────────────────
export const MOCK_PARTNERSHIPS: Partnership[] = [
  { id: 'p-1', seller_id: 'seller-1', dropping_area_id: 'area-1', status: 'approved', requested_at: d(-50), approved_at: d(-45) },
  { id: 'p-2', seller_id: 'seller-1', dropping_area_id: 'area-2', status: 'approved', requested_at: d(-48), approved_at: d(-43) },
  { id: 'p-3', seller_id: 'seller-2', dropping_area_id: 'area-1', status: 'approved', requested_at: d(-38), approved_at: d(-33) },
  { id: 'p-4', seller_id: 'seller-2', dropping_area_id: 'area-3', status: 'approved', requested_at: d(-36), approved_at: d(-31) },
  { id: 'p-5', seller_id: 'seller-3', dropping_area_id: 'area-2', status: 'approved', requested_at: d(-30), approved_at: d(-25) },
  { id: 'p-6', seller_id: 'seller-3', dropping_area_id: 'area-3', status: 'pending', requested_at: d(-5) },
];

// ─── Items ────────────────────────────────────────────────────────────────────
export const MOCK_ITEMS: Item[] = [
  {
    id: 'item-1',
    seller_id: 'seller-1',
    dropping_area_id: 'area-1',
    title: 'Vintage Denim Jacket',
    description: 'Lightly worn Levis 90s denim jacket in great condition. Size M.',
    product_code: 'DSP-001',
    amount: 850,
    base_handling_fee: 50,
    late_handling_fee: 30,
    status: 'dropped',
    dropped_at: d(-1),
    deadline_at: d(3),
    created_at: d(-7),
  },
  {
    id: 'item-2',
    seller_id: 'seller-1',
    dropping_area_id: 'area-2',
    title: 'Strawberry Jam Set (3 jars)',
    description: 'Genuine Baguio strawberry preserves, homemade. Each jar 250g.',
    product_code: 'DSP-002',
    buyer_name: 'Maria Santos',
    amount: 480,
    base_handling_fee: 30,
    late_handling_fee: 20,
    status: 'dropped',
    dropped_at: d(-2),
    deadline_at: d(2),
    created_at: d(-10),
  },
  {
    id: 'item-3',
    seller_id: 'seller-2',
    dropping_area_id: 'area-1',
    title: 'Handwoven Igorot Blanket',
    description: 'Authentic hand-woven blanket from Mountain Province. Traditional patterns.',
    product_code: 'DSP-003',
    amount: 1200,
    base_handling_fee: 80,
    late_handling_fee: 50,
    status: 'pending_dropoff',
    deadline_at: d(5),
    created_at: d(-3),
  },
  {
    id: 'item-4',
    seller_id: 'seller-2',
    dropping_area_id: 'area-3',
    title: 'Korean Skincare Bundle',
    description: 'COSRX AHA/BHA toner + TONYMOLY moisturizer + SPF. All sealed.',
    product_code: 'DSP-004',
    amount: 1650,
    base_handling_fee: 70,
    late_handling_fee: 40,
    status: 'sold',
    dropped_at: d(-10),
    deadline_at: d(-5),
    created_at: d(-15),
  },
  {
    id: 'item-5',
    seller_id: 'seller-3',
    dropping_area_id: 'area-2',
    title: 'Y2K Butterfly Top',
    description: 'Stretchy butterfly print crop top in baby blue. Tag still on, size S.',
    product_code: 'DSP-005',
    amount: 320,
    base_handling_fee: 25,
    late_handling_fee: 15,
    status: 'pending_dropoff',
    deadline_at: d(7),
    created_at: d(-2),
  },
  {
    id: 'item-6',
    seller_id: 'seller-1',
    dropping_area_id: 'area-1',
    title: 'Canon EOS 700D Kit',
    description: '18MP DSLR with 18-55mm kit lens. Minor scuffs on body, optics clean.',
    product_code: 'DSP-006',
    amount: 12500,
    base_handling_fee: 200,
    late_handling_fee: 100,
    status: 'dropped',
    dropped_at: d(-0.5),
    deadline_at: d(4),
    created_at: d(-6),
  },
  {
    id: 'item-7',
    seller_id: 'seller-2',
    dropping_area_id: 'area-1',
    title: 'BTS Map of the Soul Photocard Set',
    description: 'Complete set of 28 photocards from Map of the Soul: Persona. No duplicates.',
    product_code: 'DSP-007',
    amount: 750,
    base_handling_fee: 40,
    late_handling_fee: 25,
    // Overdue item — late fee applies
    status: 'pending_dropoff',
    deadline_at: d(-2),
    created_at: d(-12),
  },
  {
    id: 'item-8',
    seller_id: 'seller-3',
    dropping_area_id: 'area-2',
    title: 'HP Pavilion Laptop Bag',
    description: '15.6" waterproof laptop bag with USB charging port. Black, minimal wear.',
    product_code: 'DSP-008',
    amount: 580,
    base_handling_fee: 45,
    late_handling_fee: 30,
    status: 'dropped',
    dropped_at: d(-3),
    deadline_at: d(1),
    created_at: d(-8),
  },
  {
    id: 'item-9',
    seller_id: 'seller-1',
    dropping_area_id: 'area-2',
    title: 'Benguet Coffee Premium Beans 500g',
    description: 'Single-origin Arabica from Atok, Benguet. Medium roast, freshly roasted 3 days ago.',
    product_code: 'DSP-009',
    amount: 420,
    base_handling_fee: 25,
    late_handling_fee: 15,
    status: 'sold',
    dropped_at: d(-5),
    deadline_at: d(-1),
    created_at: d(-14),
  },
  {
    id: 'item-10',
    seller_id: 'seller-2',
    dropping_area_id: 'area-3',
    title: 'Adidas Stan Smith (Size 8)',
    description: 'Barely used white/green Adidas Stan Smith. Size 8 US. Box included.',
    product_code: 'DSP-010',
    amount: 2800,
    base_handling_fee: 100,
    late_handling_fee: 60,
    status: 'pending_dropoff',
    deadline_at: d(6),
    created_at: d(-1),
  },
];

// ─── Transactions ─────────────────────────────────────────────────────────────
export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-1',
    item_id: 'item-4',
    buyer_id: 'user-buyer-1',
    item_amount: 1650,
    handling_fee_applied: 70,
    total_amount: 1720,
    status: 'completed',
    created_at: d(-6),
  },
  {
    id: 'txn-2',
    item_id: 'item-9',
    buyer_id: 'user-buyer-1',
    item_amount: 420,
    handling_fee_applied: 25,
    total_amount: 445,
    status: 'completed',
    created_at: d(-2),
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    user_id: 'user-buyer-1',
    type: 'item_dropped',
    title: 'Item Ready for Pickup',
    message: 'Vintage Denim Jacket (DSP-001) has been dropped at Session Road Hub.',
    related_item_id: 'item-1',
    is_read: false,
    created_at: d(-1),
  },
  {
    id: 'notif-2',
    user_id: 'user-buyer-1',
    type: 'purchase_confirmed',
    title: 'Purchase Confirmed',
    message: 'Your purchase of Korean Skincare Bundle has been confirmed. Pick up at Mines View Hub.',
    related_item_id: 'item-4',
    is_read: true,
    created_at: d(-6),
  },
  {
    id: 'notif-3',
    user_id: 'user-buyer-1',
    type: 'fee_updated',
    title: 'Late Fee Applied',
    message: 'BTS Map of the Soul Photocard Set (DSP-007) is now past its deadline. Late fee of ₱25 added.',
    related_item_id: 'item-7',
    is_read: false,
    created_at: d(-2),
  },
  {
    id: 'notif-4',
    user_id: 'user-seller-1',
    type: 'item_dropped',
    title: 'Drop Confirmed',
    message: 'Strawberry Jam Set (DSP-002) has been confirmed dropped at Burnham Park Hub.',
    related_item_id: 'item-2',
    is_read: false,
    created_at: d(-2),
  },
  {
    id: 'notif-5',
    user_id: 'user-buyer-1',
    type: 'item_dropped',
    title: 'Item Ready for Pickup',
    message: 'Strawberry Jam Set (DSP-002) has arrived at Burnham Park Hub. Reserved for you!',
    related_item_id: 'item-2',
    is_read: false,
    created_at: d(-2),
  },
];
